# Generated by Django 4.1.1 on 2023-02-02 07:39

import campaign.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('areaofwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to=campaign.models.generate_filename)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('finish_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('organized_by', models.CharField(blank=True, max_length=500, null=True)),
                ('areaofwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='areaofwork.areaofwork')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='category.category')),
            ],
        ),
    ]
